build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64

    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3

    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3-x64
      DISTUTILS_USE_SDK: 1

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Create new conda environment
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -q conda-build anaconda-client
  #- "conda create -q -n test-environment python=%PYTHON_VERSION% cython pytest"
  #- activate test-environment
  # Configure MSVC. This should come after activating the conda envionment to
  # avoid issues with the length of PATH.
  - appveyor\build.cmd
  # Build package
  - "conda build -q conda-recipe --python %PYTHON_VERSION%"

after_test:
#  - python setup.py bdist_wheel
  - mkdir dist
  - "xcopy %MINICONDA%\\conda-bld\\*\\*.tar.bz2 dist\\"

artifacts:
  - path: dist\*
