package:
  name: demo
  version: "1.0"
 
source:
  git_rev: HEAD
  git_url: https://github.com/snorfalorpagus/appveyordemo.git
 
requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
 
test:
  requires:
    - pytest
  commands:
    - py.test tests
 
about:
  home: https://github.com/snorfalorpagus/appveyordemo
  license: Unlicense
  license_file: UNLICENSE