package:
  name: demo
  version: "1.0"
 
source:
  path: ../
 
requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
 
test:
  requires:
    - pytest

about:
  home: https://github.com/snorfalorpagus/appveyordemo
  license: Unlicense
  license_file: UNLICENSE